### ISSUE TITLE
fog in the house

### ISSUE THREAD

**Issue by InterVi** [azekillDIABLO/miniclime#2]
![screenshot_20170705_205928](https://user-images.githubusercontent.com/16702343/27878664-a7b922ba-61c7-11e7-8546-b94d4800140e.png)
It should only be done on open space. And very often it rains.

**Comment by RodrigueLemaire** [comment]
holy... this **shouldn't** happen! does it disappear after a while? and sorry for the frequent raining, i'm currently thinking to change that.

**Comment by RodrigueLemaire** [comment]
Okay, after testing, yes it does happen. But i know why! the system checks for node under you! but it doesn't check if there is something OVER you. That problematic cuz' the fog is the only weather which needs this check... _rain and snow don't._

**Comment by RodrigueLemaire** [comment]
f5d0936eb464492ac51944bee4a4ebfbf7dadfc5
